# Generated by Django 3.0.4 on 2020-03-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdo', '0002_auto_20200309_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vdo.Room'),
        ),
    ]
