# Generated by Django 3.0.4 on 2020-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdo', '0003_auto_20200309_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='MyRoomName', max_length=30),
            preserve_default=False,
        ),
    ]
