# Generated by Django 3.0.4 on 2020-03-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdo', '0004_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='token',
            new_name='person_token',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='token',
            new_name='room_token',
        ),
    ]
